### PR TITLE
Handle client requests without 'parameters'

### LINKED ISSUE #20: Server doesn't handle absent optional 'parameters'
The [Varlink spec](https://varlink.org/Method-Call) defines a client call as follows:

```
(
  method: string,
  parameters: ?object,
  oneway: ?bool,
  more: ?bool,
  upgrade: ?bool
)
```

Some Varlink implementations send an empty object as the parameter value, but others (like Python) omit it, causing a server written in this library to cut the connection instead of handling the request.

<details>
<summary>Reproducer</summary>

You can see this if you define an empty method, and use [varlink/python](https://github.com/varlink/python) to call it:

```varlink
# example/internal/varlink/stringapi/org.example.string.varlink
method Random() -> (output: string)
```
```go
// example/main.go
func (stringBackend) Random(_ *stringapi.RandomIn) (*stringapi.RandomOut, error) {
	// chosen by a fair dice roll, guaranteed to be random.
	return &stringapi.RandomOut{Output: "4"}, nil
}
```
```py
# example/repro.py
import varlink
client = varlink.Client.new_with_address("unix:./org.example.sock")
with client.open("org.example.string") as conn:
    ret = conn.Random()
```

Starting Go server and running Python client produces:

```shell
$ go generate ./...
$ cd example/
$ go build && ./example &
$ PID=$!
$ python3 repro.py
$ kill $PID
```
```
# server output
2026/01/16 15:53:39 varlink: serving connection: handling call: unexpected end of JSON input

# client output
Traceback (most recent call last):
  File "repro.py", line 4, in <module>
    ret = conn.Random()
...
BrokenPipeError: Disconnected
```

</details>

---

I'd like to discuss options on how to handle this.

- Since the spec says `parameters` key is always optional, we might want to play it safe and always check for the length of the input, so we don't crash. (Possible generated patch fixing the issue [here](https://github.com/emersion/go-varlink/commit/c32b6107e263295e775bc718d1ff13e6cd878409))
- If a method doesn't have input specified, we could further stop generating the `In` struct. (Ugly generated patch fixing the issue [here](https://github.com/emersion/go-varlink/commit/a7d19975490f4a92714c9a60841cfcd655583b69))
  - The same could probably be done with functions that return nothing.
- Both, or something in between, or something else completely.

---

AI disclaimer: This problem was discovered during LLM-based server certification development. I have confirmed the problem and wrote this bug report by hand.

### PR DESCRIPTION
**Pull request by m-horky**
Some Varlink implementations, namely the official Python one, do not include 'parameters' key in their request, if the called method takes no arguments. Previously, the server would refuse to serve such a request, returning JSON deserialization error.

Custom UnmarshalJSON method sanitizes client input and sets the 'raw.Parameters' field before the ServerRequest is forwarded to the generated code.

The second commit in this PR is code I found useful when developing and verifying this patch.

Closes: https://github.com/emersion/go-varlink/issues/20

Assisted-By: Claude Code

---

The consultation in #20 already gave me a direction, and I took this specific approach because it manages the fix on a single place, and autogenerated code living in other repositories isn't affected and gets it for free.

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -18,6 +18,22 @@ type ServerRequest struct {
 	Upgrade    bool            `json:"upgrade,omitempty"`
 }
 
+// UnmarshalJSON sanitizes a client input.
+func (req *ServerRequest) UnmarshalJSON(data []byte) error {
+	// a temporary type alias helps us unmarshall the struct
+	// without recursing into this method by accident
+	type Alias ServerRequest
```
Comment (emersion) [inline server.go]: Nit: can we use a name such as `rawServerRequest` (more descriptive, lowercase first character)?

**Review by emersion — COMMENTED** [review]
Overall looks good!

Can you add a `Signed-off-by` trailer to your commit messages to mean that you agree to the DCO? Sorry, the contribution guidelines are not yet super clear about this. See: https://docs.kernel.org/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

**Comment by emersion** [comment]
> Ah, right, I've missed that, and didn't realize since the git history didn't have it either. Fixed.

Yeah, this is specific to DCO and is only required for LLM-assisted contributions, because the copyright story is still unclear.

I've pushed a commit to make this clear: https://github.com/emersion/.github/commit/4516e08fcb78219d7c655069756baf3417a7f6e8

**Review by emersion — APPROVED** [review]
Thanks!
